{% set name = "prospector" %}
{% set version = "1.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prospector-{{ version }}.tar.gz
  sha256: d7061ac2e0ee419266c7b958f59912ed39441769d4029250a7135a6ec7440420

build:
  number: 0
  noarch: python
  entry_points:
    - prospector = prospector.run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<4.0
    - pip
    - poetry-core >=1.0.0

  run:
    - backports.zoneinfo  # https://github.com/conda-forge/django-feedstock/issues/134
    - dodgy >=0.2.1,<0.3.0
    - flake8
    - gitpython >=3.1.27,<4
    - mccabe >=0.7.0,<0.8.0
    - packaging
    - pep8-naming >=0.3.3,<=0.10.0
    - pycodestyle >=2.9.0
    - pydocstyle >=6.3.0
    - pyflakes >=2.2.0
    - pylint >=3.0
    - pylint-celery ==0.3
    - pylint-django >=2.6.1
    - pylint-flask ==0.6
    - python >=3.9,<4.0
    - pyyaml
    - setoptconf-tmp >=0.3.1,<0.4
    - toml >=0.10.2,<0.11.0
    - requirements-detector >=1.3.2

  run_constrained:
    - bandit >=1.5.1
    - vulture >=1.5
    - mypy >=0.600
    - pyright >=1.1.3
    - pyroma >=2.4

test:
  requires:
    - bandit
    - vulture
    - mypy
    - pyroma
  imports:
    - prospector
    - prospector.config
    - prospector.formatters
    - prospector.profiles
    - prospector.tools
    - prospector.tools.bandit
    - prospector.tools.dodgy
    - prospector.tools.mccabe
    - prospector.tools.mypy
    - prospector.tools.profile_validator
    - prospector.tools.pycodestyle
    - prospector.tools.pydocstyle
    - prospector.tools.pyflakes
    - prospector.tools.pylint
    - prospector.tools.pyroma
    - prospector.tools.vulture
  commands:
    # - pip check
    - prospector --help

about:
  home: https://pypi.org/project/prospector/
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'Prospector: python static analysis tool'
  dev_url: https://github.com/PyCQA/prospector
  doc_url: https://prospector.landscape.io/

extra:
  recipe-maintainers:
    - anthchirp
    - jakirkham
    - valeriupredoi
